### PR TITLE
Add support for Apple Log to the ACES OCIO config generator

### PR DESCRIPTION
**Pull request by JGoldstone**
With these changes I am able to load the generated config into ocioview, and load an image from my iPhone 15 Pro Max, and apply a standard ACES SDR for 709 rendering and ... I _think_ is rendering correctly ... but I am a programmer, and play a color scientist on TV, and most decidedly am not a cinematographer.

I would greatly appreciate someone trying this out with 'known good' Apple Log test material.

The docker variants of things are untested because I don't know docker at all.

### CODE REVIEW

**Comment by KelSolaar** [comment]
Thanks @JGoldstone,

I think we would need to do a few things here for that one to work:

1.  Update the Google Sheets spreadsheet with the Apple Log details.
2. Pull OpenColorIO from `test.pypi.org` where we have 2.4.dev. We could modify the `pyproject.toml` file by adding this:

```toml
[[tool.poetry.source]]
name = "test-pypi"
url = "https://test.pypi.org/simple/"
priority = "explicit"

[tool.poetry.dependencies]
opencolorio = {version = ">= 2, < 3", source = "test-pypi"}
```

**Comment by doug-walker** [comment]
Thanks for adding this @JGoldstone ! 

As Thomas wrote, the .csv file is not supposed to be edited by the PRs. People are supposed to edit the Google Sheet, and then the .csv is exported from that.

https://docs.google.com/spreadsheets/d/1nE95DEVtxtEkcIEaJk0WekyEH0Rcs8z_3fdwUtqP8V4/edit#gid=0

**Comment by JGoldstone** [comment]
Thanks @doug-walker ! Is that to say, then, that the changes to the Google Sheet aren't version-controlled per se, with a formal review process, because they are indirectly reviewed through the derived CSV and typically are small enough so that they could be backed out easily? (Or perhaps version control exists for Google Sheets now...)

I will make the change to the Sheet when I get into work, refresh the local CSV from that, test and resubmit. There is still an issue with the macOS-latest runner being unable to find Python 3.9 or 3.10. Not sure what that's about…

**Comment by JGoldstone** [comment]
I don't have write access to the sheet. Could I ask someone who does to look this change over and if it seems good, enter it and save it?

Proposed changes:
"Config - Transforms" sheet

above current row 180, add:

```
Colorspace: Input - Apple Log
Legacy: FALSE
Ordering: 201
CG Config: Exclude
Studio Config: Include
ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.Apple.AppleLog_BT2020.a1.v1
CLFtransformID: urn:aswf:ocio:transformId:1.0:Apple:Input:Apple_Log_to_ACES2065-1:1.0
Interface: ColorSpace
BuiltinTransform Style: APPLE_LOG_to_ACES2065-1
Linked DisplayColorSpace Style:
Encoding: log
Categories: file-io
Aliases: [blank, unless you want to add something like apple_log]
Legacy Aliases:
Legacy Family:
Reference Space: scene
Notes:
```

Above current line 185, add:

```
Colorspace: Input - Apple - Curve - Apple Log
Legacy: FALSE
Ordering: 201
CG Config: Exclude
Studio Config: Include
ACEStransformID:
CLFtransformID: urn:aswf:ocio:transformId:1.0:Apple:Input:Apple_Log-Curve_to_Linear:1.0
Interface: NamedTransform
BuiltinTransform Style: CURVE - APPLE_LOG_to_LINEAR
Linked DisplayColorSpace Style:
Encoding: log
Categories: file-io
Aliases: [blank, unless you want to add something like crv_apple_log]
Legacy Aliases:
Legacy Family:
Reference Space: scene
Notes:
```

"CG Config - Mapping" sheet

(no change)

Studio Config - Mapping sheet

Above line 7, add:

```
Ordering: 201
Colorspace: Input - Apple - Curve - Apple Log
Legacy: False
ACEStransformID: 
CLFtransformID: urn:aswf:ocio:transformId:1.0:Apple:Input:Apple_Log-Curve_to_Linear:1.0
Interface: NamedTransform
BuiltinTransform Style: CURVE - APPLE_LOG_to_LINEAR
Aliases: [blank, unless you want to add something like crv_apple_log]
Encoding: log
Categories: file-io
```

and just below that, add:

```
Colorspace: Input - Apple Log
Legacy: False
ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.Apple.AppleLog_BT2020.a1.v1
CLFtransformID: urn:aswf:ocio:transformId:1.0:Apple:Input:Apple_Log_to_ACES2065-1:1.0
Interface: ColorSpace
BuiltinTransform Style: APPLE_LOG_to_ACES2065-1
Aliases: [blank, unless you want to add something like apple_log]
Encoding: log
Categories: file-io
```

Thanks very much.

**Comment by JGoldstone** [comment]
Suggested change to pyproject.toml made, committed and pushed.

**Comment by doug-walker** [comment]
Thank you Joseph!  I made the change to the spreadsheet you requested, please let me know if you see any issues. (Note that the Studio config gets updated automatically. And note that there will be an alias generated automatically by the script, so we could discuss later if we want to modify or add to that.)

**Review by KelSolaar — APPROVED** [review]
Let's merge this one, I will do any post-merge fixes.

**Pull request merged**
