### PR TITLE
PR: Add "AP0 to sRGB AP1 - Texture" colorspace.

### PR DESCRIPTION
**Pull request by KelSolaar**
References #65.

### CODE REVIEW

**Review by doug-walker — COMMENTED** [review]
Everything looks good, but I do have a question about the naming (of course!).  The "sRGB AP1" naming seems somewhat ambiguous.  

The other similar texture spaces include the dreaded "gamma" word, but it does seem to clarify a bit.  For example, we already have spaces such as "Gamma 2.2 Rec.709".  What do you think of "sRGB Gamma AP1" or "Gamma sRGB AP1"?

And for the alias, I'll propose "srgb_ap1" --> "gsrgb_ap1".  Similar to the existing g22_rec709.

**Comment by KelSolaar** [comment]
> The other similar texture spaces include the dreaded "gamma" word, but it does seem to clarify a bit. For example, we already have spaces such as "Gamma 2.2 Rec.709". What do you think of "sRGB Gamma AP1" or "Gamma sRGB AP1"?

image

Sadly this is the most concise and comprehensible at this point, other alternatives:

- Non Linear sRGB / sRGB Non Linear 
- Encoding sRGB / sRGB Encoding
- Inverse EOTF sRGB / sRGB Inverse EOTF

**Comment by doug-walker** [comment]
My preference would be "sRGB Encoded AP1".  But I want to defer to you for the final call.  I don't want to make you "Drown In Your Own Tears".

So please dry your eyes Thomas, I don't want you to challenge Aretha Franklin at that.  :) 
With some help here from Atlantic's Jerry Wexler and the Muscle Shoals rhythm section, she captured the emotion pretty well:
https://www.youtube.com/watch?v=OqdH07zXuVc

**Comment by KelSolaar** [comment]
@doug-walker : Changes implemented!

**Review by doug-walker — APPROVED** [review]
Awesome, thank you Thomas!

There are still a few issues with aliases, but this fixed the majority of them.  The remaining ones are:
- "ACES" prefix missing from legacy name of first 9 spaces in the spreadsheet.
- "Utility" prefix missing from legacy name of Raw color space.
- P3-D65 alias has a dash (unlike the 1.2 config)
- The "sRGB - Texture" color space has an alias "srgb" which I worry is too short and could conflict with other usage.  The 1.2 config did not have this as a name.  I don't know where this is coming from since it is not in the "Aliases" column of the spreadsheet.  Is the slugify dropping "texture"?

**Comment by KelSolaar** [comment]
Thanks @doug-walker, I will merge this one, and rebase #76 on top of main as it includes those commits and we will address the last bits there!

**Pull request merged**
