### PR TITLE
Updating Github Actions and speed up git clones

### PR DESCRIPTION
**Pull request by grische**
* CI workflow: Adding `ubuntu-latest` to the OS matrix
* CI workflow: Updating actions to use their newer version. One notable change is the introduction of shallow cloning by default in checkout@v2.
* Dockerfile: shallow clone the "throwaway" OpenColorIO repository inside the container

### CODE REVIEW

**Comment by grische** [comment]
@michdolan I rebased it once again, to see if the CLA has recovered by now.

**Comment by doug-walker** [comment]
GitHub is deprecating Node.js 16, so these actions will need to be revved again (e.g., checkout@v4). If someone wants to do a PR we will endeavour to merge it in fewer than two years this time!   :(

**Comment by KelSolaar** [comment]
I’m planning to do a stack update PR soon!

Thomas Mansencal - colour-science.org <https://www.colour-science.org> -
thomasmansencal.com <http://www.thomasmansencal.com>

**Comment by KelSolaar** [comment]
Closing this one in favour of #126, I cherry-picked 80069f4, thanks a lot @grische!

**Pull request closed without merging**
