### PR TITLE
Add CG config CLF source

### PR DESCRIPTION
**Pull request by michdolan**
This adds @doug-walker 's CLF generation code for the CG config, with adjustments to match code conventions from the rest of the config generation package. Thanks @doug-walker for contributing these!

I also tracked down the source of the P3-D65 ST2084 color spaces having a `sdr-video` encoding instead of `hdr-video`. What I found was that this was coming from the reference config CSV data, and when adopting a reference config color space in a downstream config's CSV (by referencing an aces-dev transform ID), the color space parameters are ignored with the reference config color space definition taking precedence. To better communicate this, I cleared all values from the CG config CSV that will not affect the CG config. Whether that's what we want long term, vs. being able to override those properties in an inheriting config's CSV, can be discussed down the road.

Note: The CLF matrix numbers have changed in later decimal places, since the matrices are being provided from `colour` instead of their previous source in Doug's env.

### CODE REVIEW

**Comment by michdolan** [comment]
Updated CG config: https://gist.github.com/michdolan/215b894a145eb7e5133904fb0dfa25c3

**Review by doug-walker — APPROVED** [review]
Awesome work, thank you so much Michael!   (And much nicer than my prototype!  :)  )

**Comment by KelSolaar** [comment]
LGTM! Thanks for tracking down the various issues mentioned!

**Comment by KelSolaar** [comment]
@michdolan: I will merge but my only question is pertaining to the CSV files: Did you update the Google Spreadsheets accordingly? We should do it otherwise we will lose your changes next update.

**Pull request merged**
