### PR TITLE
PR: ACES 1.x Varnishing

### PR DESCRIPTION
**Pull request by KelSolaar**
This PR updates various aliases and names according to VWG discussions and also sets the *Un-tone-mapped* view transform first in the list of view transforms for **OCIO** profiles <=2.3.

### CODE REVIEW

**Comment by KelSolaar** [comment]
@doug-walker: This should also include the new names from #127.

**Comment by doug-walker** [comment]
Thanks Thomas, I've reviewed the CG and Studio artifacts and will suggest the following changes:

1) Please change "CIE-XYZ-D65 - Scene-referred" to "CIE XYZ-D65 - Scene-referred" (note the dash to space).

2) Please add the following aliases:
g18_rec709_scene
g22_rec709_scene
g22_ap1_scene
lin_ciexyzd65_display
cie_xyz_d65_display

3) Please remove the following aliases:
CIE-XYZ-D65 - Display-referred
cie_xyz_d65_display_referred

4) The alias "cie_xyz_d65" was in the previous config and removed from the new one. I think this is probably the correct thing to do since it is now ambiguous, but wanted to mention it in case others feel we need to continue to support it.

5) The Un-tone-mapped View Transform moved for the earlier CG configs but not the Studio configs.  If it's easier, you could make it always first regardless of version or config.

**Comment by KelSolaar** [comment]
Should not be too far now! Sorry about 5., completely forgot to add the code to the Studio Config.

**Review by carolalynn — DISMISSED** [review]
These are looking great, Thomas! I don't think I have any additional notes from what Doug mentioned.

**Comment by doug-walker** [comment]
I'm wondering if the ordering of the Utility family could be improved.  Currently it is this:
```
ITU/Camera Rec.709
Linear P3-D65
Linear Rec.2020
Linear Rec.709 (sRGB)
CIE XYZ-D65 - Scene-referred
Gamma 2.2 Encoded AdobeRGB
Gamma 2.2 Encoded AP1
Gamma 2.4 Encoded Rec.709
Linear AdobeRGB
sRGB Encoded AP1
sRGB Encoded P3-D65
Gamma 1.8 Encoded Rec.709
Gamma 2.2 Encoded Rec.709
sRGB Encoded Rec.709 (sRGB)
Raw
ST-2084 - Curve
Rec.1886 - Curve
ITU/Rec.709 - Curve
sRGB - Curve
```
Perhaps an ordering along these lines would be better?  Any opinions?
```
sRGB Encoded Rec.709 (sRGB)
Gamma 1.8 Encoded Rec.709
Gamma 2.2 Encoded Rec.709
Gamma 2.4 Encoded Rec.709
ITU/Camera Rec.709
sRGB Encoded P3-D65
Gamma 2.2 Encoded AdobeRGB
sRGB Encoded AP1
Gamma 2.2 Encoded AP1
Linear Rec.709 (sRGB)
Linear P3-D65
Linear AdobeRGB
Linear Rec.2020
CIE XYZ-D65 - Scene-referred
Raw
sRGB - Curve
Rec.1886 - Curve
ITU/Rec.709 - Curve
ST-2084 - Curve
```

**Comment by doug-walker** [comment]
Items 1-5 above have been addressed!

Here's a few other observations. I don't think they require action, but are probably worth noting.

6. The versioning of the new configs is as follows:
	studio-config-v2.1.0_aces-v1.3_ocio-v2.1.ocio
	studio-config-v2.1.0_aces-v1.3_ocio-v2.2.ocio
	studio-config-v2.2.0_aces-v1.3_ocio-v2.3.ocio
	studio-config-v2.2.0_aces-v1.3_ocio-v2.4.ocio

Note that the color space version is sometimes 2.1.0 and others 2.2.0, even though the contents of all of these is basically the same in terms of the updated naming of existing color spaces.  One could argue that the ones that are 2.1.0 are correct in the sense that the previous version of those configs was 2.0.0.  Alternatively, one could argue that it's simpler for people if "color space version 2.1" always means basically the same thing, even if that means skipping a version.  I have no objections to the current scheme, but wanted to mention it.

7. In this latest drop, the "CIE-XYZ-D65" alias was removed.  This was a color space name (not an alias) in the previous config releases.  However, it was in the inactive_colorspaces list, and so it does seem reasonable that we could remove it without even keeping an alias.  I have no objections since it has become too ambiguous, but wanted to mention it.

**Comment by KelSolaar** [comment]
> 7\. the "CIE-XYZ-D65" alias was removed

Yes, this was also done for disambiguation!

Colorspace(s) and NamedTransform(s) should be ordered as per-above suggestion!

**Review by doug-walker — APPROVED** [review]
Thanks for all the changes Thomas, these look great!

There is one more small naming issue currently being discussed, so I'm not sure if you prefer to merge this now or wait, but I'll approve now to give you the flexibility.

**Comment by KelSolaar** [comment]
Let's wait for the naming issue resolution.

**Comment by KelSolaar** [comment]
Merging for now because https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/2039 is up and ready!

**Pull request merged**
