### PR TITLE
PR: Prefix node names to ensure uniqueness.

### PR DESCRIPTION
**Pull request by KelSolaar**
This PR addresses the finding by @doug-walker that some of the Sony IDTs were missing. The reason is simple, the nodes in the graph need to have unique names and unfortunately, some of the Sony IDTs and CSCs had the same short name. Fixed by prefixing the node names with their type.

References #AcademySoftwareFoundation/OpenColorIO#1193.

### CODE REVIEW

**Review by doug-walker — APPROVED** [review]
LGTM

**Comment by doug-walker** [comment]
One question ... The ACEStransformID strings for IDT.Sony.SLog3_SGamut3.ctl and ACEScsc.Academy.SLog3_SGamut3_to_ACES.ctl are different, so why were they getting the same node names?

In any case, I do think it's nice to be pre-pending the "type" to the node names, so no objections to the PR.

**Comment by KelSolaar** [comment]
> One question ... The ACEStransformID strings for IDT.Sony.SLog3_SGamut3.ctl and ACEScsc.Academy.SLog3_SGamut3_to_ACES.ctl are different, so why were they getting the same node names?

This is a good question! The nodes in the graph (and the resulting config) are colourspaces, thus during the parsing of the `ACEStransformID`, the code tokenizes the `name` component on `_to_` to find out the source and target colourspaces for a given CTL file, alternatively, depending on the `type`, it can be inferred automatically:

- `IDT.Sony.SLog3_SGamut3` is inferred to be from `SLog3_SGamut3` to `ACES2065-1` because it is an IDT.
- `ACEScsc.Academy.SLog3_SGamut3_to_ACES` is a CSC it is tokenized to get the source and target.

Does it make sense?

**Comment by doug-walker** [comment]
Yes, it makes sense.  Thank you Thomas!

**Review by michdolan — APPROVED** [review]

**Pull request merged**
