### PR TITLE
Add CLF for RED Log3G10-RWG

### PR DESCRIPTION
**Pull request by doug-walker**
Adds code to build the RED Log3G10-RWG CLF, along with the built CLF file itself.

Our thanks to RED Digital Cinema for validating this CLF for numerical accuracy as well as the metadata/IDs.

Changes the name of two tasks, given that there are now both utility and input CLFs:
build_clf_utility --> build_clfs
docker_run_build_clf_utility --> docker_run_build_clfs

Signed-off-by: Doug Walker <doug.walker@autodesk.com>

### CODE REVIEW

**Comment by doug-walker** [comment]
Unit tests are failing because the "transform type" extracted from the ID is not in ["Input", "Utility"].  The ID that we proposed to RED is "urn:aswf:ocio:transformId:1.0:RED::Log3G10_RWG_to_ACES2065-1:1.0".  So let's discuss at the working group meeting whether we need to update the ID or the test.

**Comment by doug-walker** [comment]
I got the unit tests to pass by adding 11 instances of "# doctest: +SKIP" in clf/discover/classify.py.   But I'm hesitant to go with that approach (did not push a commit yet).

Is that expected, or is there a better way?

**Comment by KelSolaar** [comment]
> I got the unit tests to pass by adding 11 instances of "# doctest: +SKIP" in clf/discover/classify.py. But I'm hesitant to go with that approach (did not push a commit yet).
> 
> Is that expected, or is there a better way?

Let me look at that tonight!

**Comment by KelSolaar** [comment]
@doug-walker: I don't remember what was the resolution on the `id` for the RED CLF but if we add `Input`, i.e. `id="urn:aswf:ocio:transformId:1.0:RED:Input:Log3G10_RWG_to_ACES2065-1:1.0"`, all the tests seem to run fine here:

```
(opencolorio-config-aces-BRlYASVn-py3.9) Eris:OpenColorIO-Config-ACES kelsolaar$ invoke tests
===============================================================================
*                                                                             *
*   Running "Pytest"...                                                       *
*                                                                             *
===============================================================================
============================= test session starts ==============================
platform darwin -- Python 3.9.12, pytest-7.1.1, pluggy-1.0.0
rootdir: /Users/kelsolaar/Documents/Development/opencolorio/OpenColorIO-Config-ACES
plugins: cov-3.0.0
collected 31 items

opencolorio_config_aces/clf/discover/classify.py ....                    [ 12%]
opencolorio_config_aces/config/cg/generate/tests/test_resources.py .     [ 16%]
opencolorio_config_aces/config/reference/discover/classify.py ....       [ 29%]
opencolorio_config_aces/config/reference/discover/graph.py .....         [ 45%]
opencolorio_config_aces/config/reference/generate/analytical.py .        [ 48%]
opencolorio_config_aces/config/reference/generate/config.py ......       [ 67%]
opencolorio_config_aces/config/reference/generate/tests/test_resources.py . [ 70%]
                                                                         [ 70%]
opencolorio_config_aces/utilities/common.py .s....s..                    [100%]

================== 29 passed, 2 skipped, 1 warning in 10.08s ===================
(opencolorio-config-aces-BRlYASVn-py3.9) Eris:OpenColorIO-Config-ACES kelsolaar$
```

**Comment by doug-walker** [comment]
Following up on the discussion at last week's meeting, I've pushed another commit that changes the RED transform ID from: 
"urn:aswf:ocio:transformId:1.0:RED::Log3G10_RWG_to_ACES2065-1:1.0" to:
"urn:aswf:ocio:transformId:1.0:RED:Input:Log3G10_RWG_to_ACES2065-1:1.0"

Even though we decided to add "Input" to the ID, we agreed that an empty token in that position was legal, so I modified classify.py to accept that too.

@KelSolaar , @michdolan , the unit tests now pass, so if one of you could approve we could go ahead and merge this.

**Review by KelSolaar — APPROVED** [review]
LGTM!

**Pull request merged**
